((nil . ((indent-tabs-mode . nil)
         (tab-width . 2)
         (fill-column . 80)
         (c-basic-offset . 2)
         ;;(java-mode . ((c-basic-offset . 2)))
         (buffer-file-coding-system . utf-8-unix))))
